services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

  emailservice:
    build:
      context: .
      dockerfile: Dockerfile.emailservice
    container_name: emailservice
    depends_on:
      - rabbitmq
    ports:
      - "3030:3030"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/cadastro
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - ./src:/api
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./app:/web
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge