FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY ["src/Api/", "Api/"]
COPY ["src/Application/", "Application/"]
COPY ["src/Domain/", "Domain/"]
COPY ["src/Infrastructure/", "Infrastructure/"]

RUN dotnet restore Api/Api.csproj

WORKDIR /src/Api

EXPOSE 5000

CMD ["dotnet", "run"]