FROM node:22.14.0-alpine@sha256:9bef0ef1e268f60627da9ba7d7605e8831d5b56ad07487d24d1aa386336d1944

WORKDIR /app

COPY app/. .

RUN npm install

# Defina a porta que o React deve usar
ENV PORT=9090

EXPOSE 9090

# Inicia o servidor React
CMD ["sh", "-c", "npm start"]